spring.data.mongodb.uri=mongodb://localhost:27017/synapse-forge
server.port=8081
spring.application.name=synapse-forge-db
mailtrap.api.token=5c8718f85929d877add132ed935dc635
mailtrap.from.email=hello@demomailtrap.co
mailtrap.from.name=Synapse Forge
